name: secret_workflow_repository

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step with a secret from THE REPOSITORY
        run: |
          echo "Hello World"
          echo "This is a secret value in this repository: ${{ secrets.SECRET_VALUE }}"
  job2:
  environment: production_secret
  runs-on: ubuntu-latest
  steps:
    - name: Run Commands with a Secret FROM THE ENVIRONMENT (production)
      run: |
        echo "Hello World!"
        echo "This is a secret value in production envronment: ${{ secrets.SECRET_VAL }}"  
        echo "Production variable: ${{ env.PRODUCTION_VARIABLE }}"      